### ISSUE TITLE
development FAQ notes

### ISSUE THREAD

**Issue by dcsan** [mistval/kotoba#106]
Some general questions that came up. Maybe this could be an FAQ for others who want to hack on the bot...

## dev/restart loop
I created a `nodemon ..` task to restart when code changes,
but it doesn't seem to reload/pickup any changes in commands.
It seems that's deeper in monochrome...

## monochrome 'ejected'
monochrome is an NPM module. to modify that...
wondering if you have a setup to just use local monochrome code
so i don't have to modify the NPM module.
If i just dump monochrome src into eg `bot/framework/` and require it from there...
it should work i guess?

## uniqueId
uniqueId: 'state12345',
does this have to be unique across all instances?
why can't we create internally like `bot.id + action`

## testing
since these are text in/out, very well suited for testing
wonder if you have a simple test framework somewhere?

## typescript typings
i like TS! wonder if you have typings so i could get intellisense etc.
maybe Eris does, but that's not really used here.

## how do I get at the `config` or other bot variables?
I looked at `bot.config` on the action params but doesn't seem to be there.
just require the config for now.

## heap dumps
I think nodemon restarting is causing some kind of heapdump.

**Comment by mistval** [comment]
## dev/restart loop

Personally I use the VS code debugger and hit F5 to restart. I guess nodemon probably doesn't restart when you change commands because they are dynamic required.

## monochrome rejected

I'd recommend cloning the monochrome repo next to kotoba, and then in kotoba you can do `npm install ../monochrome` to install monochrome from disk. Then any changes you make in monochrome will be reflected in kotoba.

## uniqueId

This just needs to be unique across other commands. If it's not, it will error and tell you when you start the bot. I don't remember why I put random numbers in them, I was probably drunk or something, and overly concerned about collision. You can use basically whatever you want. I'd make it the same as the command name.

## testing

I don't have any automated tests, but you're welcome to add a testing framework if you'd like. Since the commands and stuff are pretty modular, I've been able to get away with just manually testing the areas I change.

## typescript typing

I don't have any unfortunately, as I don't use typescript myself. Eris does have them, though they don't seem to advertise it, I couldn't find much about it by Googling. Monochrome does have JSDoc comments, I'll try to automatically generate TS bindings from them and see if it gives me anything useful.

## how do I get at the config or other bot variables?

Requiring the config is also what I do.

## heap dumps

That's strange, there is a heapdump command but I can't imagine how that could execute unless you invoke the command from inside Discord.

**Comment by mistval** [comment]
I haven't had luck trying to generate a TS definition from the JSDoc comments, I don't think that's going to work.

**Comment by mistval** [comment]
Heap dump has been removed as a dependency in master.
