### ISSUE TITLE
server rendering images

### ISSUE THREAD

**Issue by dcsan** [mistval/kotoba#107]
making an issue here to memo some of our discussion

many features would benefit from a stable way to render images with text server side as bitmaps so that discord can display inline.
however node-canvas relies on Cairo, and other libraries imagemagick/ various complex tools.

it would be great to have a lightweight and not too slow 'no dependencies' method to generate images.

some candidates / details below

https://www.bmglyph.com/

**Comment by dcsan** [comment]
# node-jimp 
has a text feature but i think its using images for the fonts. not sure how/if that would work for kanji fonts
https://medium.com/@rossbulat/image-processing-in-nodejs-with-jimp-174f39336153
> Remember, you can only export one size - colour combination for each font, therefore it is likely you will need to load multiple fonts into your image processing scripts.

**Comment by dcsan** [comment]
## sharp
https://www.npmjs.com/package/sharp
much simpler / less deps required server image render lib
but no text features I can see in the current API
could be good for just compositing files together

**Comment by mistval** [comment]
I think node-jimp probably won't work because of how fonts work in it. Kotoba users can change the font family / color / size in the bot settings. It sounds like in order to use node-jimp I would need to provide it with BMPs for every possible combination.

It looks like sharp can render SVGs so there might be potential there if we had something that could render text into an SVG, though that would probably have native dependencies too.

**Comment by dcsan** [comment]
looks like sharp supports text fonts etc, but also has some upstream dependency issues
https://github.com/lovell/sharp/issues/1836

If you have fairly simple templates you can probably avoid that `dx` property.
another nice thing is that SVG can be used as a human-readable template easily to insert values into...

**Comment by mistval** [comment]
Our best bet for removing these woes might just be upgrading to the latest version of canvas since it now automatically downloads binaries and building and installation is not required, if they have a binary for your platform.

The supported platforms are here: https://github.com/node-gfx/node-canvas-prebuilt/releases

Unfortunately there are breaking changes and the furigana rendering code will need to be largely rewritten. I'll see if I can do that this weekend.

**Comment by dcsan** [comment]
I quite like SVG because you can design a layout (eg sketch on the mac) and then just add your variables to template into it.
I just did a very quick test with sharp and it renders SVG with text fine, however it doesn't seem to pick up on locally installed fonts. I'll have to look into that further

original SVG

![image](https://user-images.githubusercontent.com/514002/63287276-e3e5d100-c2b1-11e9-94a1-270a93fc7aa8.png)

rendered to transparent png

![image](https://user-images.githubusercontent.com/514002/63287263-d892a580-c2b1-11e9-97ce-7f84ec39393a.png)

**Comment by dcsan** [comment]
hacky code + test svg files here

https://github.com/dcsan/kotoba/tree/2-snapshots/snappy

**Comment by dcsan** [comment]
update: it works well for basic ZH/JA kanji but i can't get custom fonts to work with some messing around. not sure if we'll get any help from sharp project
https://github.com/lovell/sharp/issues/1844

**Comment by mistval** [comment]
Do you have any idea of the performance characteristics of doing it this way? For the quiz feature, rendering needs to be very fast, preferably 10 ms or less for an image like this:

![](https://cdn.discordapp.com/attachments/268319988216102912/613192170177953887/upload.png)

**Comment by dcsan** [comment]
I don't but sharp npm does talk a lot about how speed optimized it is.
they have a performance comparison here
https://sharp.pixelplumbing.com/en/stable/performance/
reading a large JPG and resize/sampling at   26.45 ops/sec
= 37ms / per on a c5.large instance 

however i guess this is all just for bitmap stuff and much larger files where IO will be an issue.
the SVG renderer calculation would be the bottle neck in your case

under the hood sharp seems to use 
libvips
https://github.com/libvips/libvips
which uses
https://gitlab.gnome.org/GNOME/librsvg
which is a gnome project so ... cairo
https://www.cairographics.org/

so, while sharp installed seamlessly for me, maybe it does have the same potential problems. 

I guess it depends which format you like most?

For me the benefit of SVG is that I can use a design tool to do the layouts and get human readable svg text file as output to edit as templates.
A benefit of canvas would be if you were doing games and needed a faster renderer or sprite animation. I don't think SVG realtime renderers are that optimized.

There's also lots of other things that render to SVG, eg D3, if you were doing a "map" of how different words relate together.

**Comment by mistval** [comment]
I'm not that keen on the idea of fundamentally changing any of the stuff I already have, especially considering the uncertainties and opportunity cost, but I'd like to be able to update the Node version eventually and it would be nice if it was easier to install since it sounded like cairo is problematic on Mac. I think the latest version of canvas wouldn't be a problem for Mac as I see it has darwin builds in its repo, so there shouldn't be any build step. So updating the canvas version is sounding like the best option to me. We can also add other libraries though if you or anyone else wants to use them for new features, that's fine by me.

**Comment by dcsan** [comment]
yep i can certainly see that if you've got a lot of time invested (sunk costs fallacy notwithstanding). 

for me for new stuff SVG + sharp looks like a good option, but no custom fonts is very limiting design-wise.

**Comment by mistval** [comment]
I've updated the canvas version used in master to 2.6.0. It shouldn't give you any trouble installing. It should download the binaries for your architecture from their repo without requiring a node-gyp build step.

**Comment by mistval** [comment]
Kotoba now installs without any node-gyp step required on most systems (pre-built binaries are downloaded for the native packages).
