### ISSUE TITLE
"file:../node-common",

### ISSUE THREAD

**Issue by dcsan** [mistval/kotoba#108]
noticed this in the package.json

      "kotoba-node-common": "file:../node-common",

note that this doesn't seem to work with yarn, which uses something like `link: ..` syntax. I've had a lot of problems with this... 
are you on windows? otherwise symbolic links maybe one way around it, tho I also haven't got that to work reliably. esp for non 'develop only' deps ie stuff you need deployed and available at runtime.

overall a bit of a painful area. I've been trying to find a good way to share type definitions from typescript across projects.

**Comment by mistval** [comment]
I am on Windows most of the time, and other potential contributors might be too, so I think it would be best to have a solution that works on any OS. Is using NPM an option for you?

**Comment by dcsan** [comment]
using NPM is fine for me, it just makes things fragile since many use yarn.

I also have to support windows users on another project and haven't found a good way to deal with this, especially for fast-changing shared libs.

another issue is it means whatever production env. will need the `../` dir as part of the deployment, so the bot is less "stand-alone". unless you can make some stuff part of `devDeps` only, and then do all the magic to set flags like: `NODE_ENV=production npm install` 
But i guess that won't work in this case cos they're runtime libraries.

a separate NPM package is the other way, but makes life more complex, esp for updates.

**Comment by mistval** [comment]
Needing to have `../` to run the bot sounds fine to me. It's already required for the config file, docker-compose.yml, and worker process.

FWIW I think the `file:` thing is supposed to be a development feature and isn't really "supposed" to be used in production, but it was the best way I could find for doing this. Separate NPM packages imported via .git URI would probably be a more correct thing to do, but adds some overhead to development.

As for yarn, doesn't that also treat dependencies a bit differently and generate a `yarn.lock` file and such? I know a lot of people prefer yarn but I'd be more comfortable sticking to NPM for this project since everyone has it installed anyway.

**Comment by mistval** [comment]
This is working well with NPM. I would ask contributors to Kotoba to use NPM.
