### ISSUE TITLE
User suggestion: TOEIC and part-of-speech English decks

### ISSUE THREAD

**Issue by mistval** [mistval/kotoba#111]
"TOEICで出てくる単語のDECKや日常会話で使われるような単語のDECKがあれば嬉しいです。
今も毎日使わせて頂いていますが、あまり日常会話で使われないような単語が多いです。もう少し動詞・名詞などのようにジャンルで分けて頂けると幸いです。"

**Comment by dcsan** [comment]
JFYI TOEIC is some weird proprietary stnadard that's only really popular in japan, tho for that it's popular. otherwise worldwide TOEFL (for US universities) and IELTS most other places.

sure you know but you can scrape decks from quizlet.
what other sources have you found for getting easily re-formattable decks? I think anki last time i looked used some binary format or maybe it was just a bit convoluted.

**Comment by mistval** [comment]
That's good to know. This was a request from a JP learner of English, so TOEIC might be a good place to start.

I've never used quizlet and the existing decks I have come from a whole bunch of different sources, mainly scraping various websites and dictionaries and looking up readings and definitions from Jisho.org as needed. The only deck I've generated from an Anki deck is my personal one (k33). Anki can export to CSV but depending on the author they might put random HTML tags in their cards or have really irregular formatting or such that makes it hard to process.
