### ISSUE TITLE
WOTD stopped working

### ISSUE THREAD

**Issue by ernespa** [mistval/kotoba#160]
Since the last changes 3 days ago we're not getting daily words in our server. Also the command 'k!help wotd' returns the general help.

I've copied the repository to test it locally and strangely it works fine. I have the real bot and the local one in the same server and they both respond to the same commands, and I'm getting diferent results for the 'k!help wotd' command. I've kicked and re-invited the bot just in case and run npm ci so it should be exactly the same bot, but the remote one is behaving as if the command wotd doesn't exist at all.

**Comment by mistval** [comment]
Hi, I had to disable it due to a problem and am currently refactoring it. It will probably be back this weekend.

It looks like the timer offset managed to get larger than the maximum, which makes `setTimeout` default to one millisecond apparently. This led to CPU exhaustion on the bot server and massive spam to some users.

**Comment by mistval** [comment]
It's back now, but all schedules have been cleared and will need to be recreated.
