### ISSUE TITLE
Save conquest mode because of consecutive unanswered questions

### ISSUE THREAD

**Issue by Alkhwarizm** [mistval/kotoba#84]
I have a suggestion to make it possible to resume quiz (particularly the conquest mode) when it ended because of consecutive unanswered questions. 

My friend was doing a long game of conquest mode when suddenly he lost connection and cannot get it back in time to save his game. The quiz has ended and he lost all of his progress. It's to avoid such unfortunate turn of event. 

My suggestion is to just save the quiz when in conquest mode instead of ending it when the consecutive unanswered question limit is reached.

**Comment by mistval** [comment]
👍 I would like to do this when I have time. In the meantime, I can restore his last save if you'd like. If you give me his Discord user ID then I can find and restore the save. My support server is here: https://discordapp.com/invite/f4Gkqku

**Comment by mistval** [comment]
Your friend emailed me their username so I restored the save for them.

**Comment by mistval** [comment]
I added a recycling bin that you can load discarded saves from. It will appear when you say **k!quiz load**. I'm not sure if this is better or worse than automatically saving if too many questions are missed in a row (in that case you would end up having to repeat all the cards you missed even if you know them). In any case it was easier to implement this way, and there have also been some people who accidentally said **k!quiz stop** instead of **k!quiz save** so this helps them too. I'll leave this issue open so I can reconsider other solutions when/if I get around to doing the desperately needed "grand refactor" that would give me a chance to design better for these eventualities.

So if someone has a poor connection I would suggest they just save frequently so they can recover from the recycling bin.

**Comment by mistval** [comment]
Hopefully the recycling bin addition has been sufficient. I'm going to close this but feel free to reopen if you feel strongly that automatically saving would be a better solution.
